name: Check Style

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout module
        uses: actions/checkout@v6

      - name: Check Symcon PHP style
        uses: symcon/action-style@v3
